qbot:
  version: 1.0.0
  url: 192.168.2.158:5700
  botqq: 2023311861
  adminqq: 2632938870
server:
  port: 9011
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: QQBot
  profiles:
    active: dev

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: 'http://192.168.2.158:11111/xxl-job-admin'
    executor:
      appname: 'qbot'
      address: 192.168.2.92
      port: 9012
# 配置swagger文档的访问路径
# open api配置
springdoc:
  packages-to-scan: com.orange.qqbot.entrance
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
#plumelog:
#  appName: QQBot
#  kafkaHosts: 121.41.168.174:9092